baseURL = "https://gaius.coffee/lastreverie/"
languageCode = "en-us"
title = "Last Reverie"
theme = "hyde"

[params]
    description = "Pen & Paper TTRPG \n Inspired by Final Fantasy \n Powered by the Apocalypse"

[menu]
    [[menu.main]]
        name = "Download"
        url = "/pages/download"
    [[menu.main]]
        name = "Character Builder"
        url = "/pages/builder"
